### ISSUE TITLE
Please check similar plugins

### ISSUE THREAD

**Issue by pcav** [SMByC/ThRasE#1]
http://plugins.qgis.org/plugins/Serval/seems partly overlapping. Please consider merging the two, as this would be better both for the users and for the managers, and in the long term also for you.
Thanks.

**Comment by XavierCLL** [comment]
Hi Paolo,

Yes of course, I have tried the Serval plugin, but Serval is very limited plugin for edit the thematic raster maps, it only has a pixel picker tool and you need set each pixel value every time and only for one pixel. ThRasE can do that easier and faster for the user and has several editing tools.

Anyway, thanks for mention it! I am open to hear ideas or features to implement to ThRasE. If you know a good specific feature not implemented in Thrase please open an issue with that :)

**Comment by pcav** [comment]
Thanks for th explanation. Would you mind contacting the author of Serval plugin to see if he's interested in merging the works? Sorry to insist, but having duplication of similar plugin is a significant proble for us.
Please let me know if you need help.

**Comment by XavierCLL** [comment]
Hi Paolo, right now is not possible to join efforts due the plugins has different targets:

ThRasE: specific for edit thematic raster (integer values)
Serval: possibility to edit any kind of raster

**Comment by pcav** [comment]
Thanks for the reply. Isn't all kind of raster a superset of thematic raster?

**Comment by XavierCLL** [comment]
Hi Paolo, yes, of course, but Serval is a plugin to edit one pixel at a time, simpler tool, instead ThRasE has several special features for edit thematic rasters (tangled up for (maybe pointless) expanding these feature to non-integer values)

**Comment by pcav** [comment]
It makes sense to me, thanks for the explanation.
